[[rules]]
path = "/etc/passwd"
expected_mode = 644
importance = "Medium"

[[rules]]
path = "/etc/shadow"
expected_mode = "600"
importance = "High"


[[rules]]
path = "/var/log/btmp"
expected_mode = "u=rw,g=,o="
importance = "Low"

